-- phpMyAdmin SQL Dump
-- version 4.0.9
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 27-04-2014 a las 11:05:15
-- Versión del servidor: 5.6.14
-- Versión de PHP: 5.5.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `carrito`
--
CREATE DATABASE IF NOT EXISTS `carrito` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
USE `carrito`;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `articulo`
--

CREATE TABLE IF NOT EXISTS `articulo` (
  `idarticulo` int(1) NOT NULL AUTO_INCREMENT,
  `idcategoria` int(1) NOT NULL,
  `articulo` varchar(45) COLLATE utf8_spanish_ci NOT NULL,
  `descripcion_corta` varchar(100) COLLATE utf8_spanish_ci DEFAULT NULL,
  `descripcion_completa` varchar(1000) COLLATE utf8_spanish_ci NOT NULL,
  `precio` decimal(10,2) NOT NULL,
  `existencias` int(6) NOT NULL,
  `fecha_registro` date NOT NULL,
  `imagen` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`idarticulo`,`idcategoria`,`articulo`),
  KEY `fk_articulo_categoria_idx` (`idcategoria`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci AUTO_INCREMENT=85 ;

--
-- Volcado de datos para la tabla `articulo`
--

INSERT INTO `articulo` (`idarticulo`, `idcategoria`, `articulo`, `descripcion_corta`, `descripcion_completa`, `precio`, `existencias`, `fecha_registro`, `imagen`) VALUES
(1, 1, 'Almost Pwdr SPF15 Fair Clinique', 'Protege tu rostro de los rayos UV y luce un cutis sin imperfecciones con el maquillaje Clinique.', 'Protege tu rostro de los rayos UV y luce un cutis sin imperfecciones con el maquillaje Clinique.Color: Fair.\nTipo de Producto: Facial.\nIngredientes: Antioxidantes.\nCapacidad: 9 gr.\nPresentación: Polvo.\nGénero: Mujer.', '465.00', 2, '2014-04-26', 'productos/belleza/Almost Pwdr SPF15 Fair Clinique 9 gr.jpg'),
(2, 1, 'Base de maquillaje en crema', 'Proporciona un acabado natural, ligeramente mate debido a los polvos.Tipo de producto: Rostro', 'Base de maquillaje en crema.\nColor: Proporciona un acabado natural, ligeramente mate debido a los polvos.\nTipo de producto: Rostro.\nIngredientes: Contiene difusores ópticos que suavizan las líneas de expresión y consiguen un aspecto fresco y perfecto.\nCapacidad: 10 gm.\nPresentación: Base de Maquillaje.\nGénero: Mujer.', '485.00', 1, '2014-04-26', 'productos/belleza/Base de maquillaje en crema.jpg'),
(3, 2, 'Aspiradora Koblenz Plata AG-1200', 'Aspiradora Koblenz, apta para mantener tu casa limpia, libre de ácaros y partículas nocivas para la ', 'Características generales: Aspiradora con Novedoso sistema a base de filtración de agua que atrapa el 99.97% de las partículas nocivas para la salud.\nMarca: Koblenz.\nModelo: AG-1200.\nColor y diseño: Plata con negro.\nNiveles de programación: Sistema de filtración de 5 niveles (Filtro de agua, filtro hepa, filtro de hule espuma, filtro de salida de aire y filtro del motor).\nPanel de mando: Pedal de encendido.\nFunciones Especiales: Construcción en ABS de alto impacto, Cable retráctil de 5 m, Variad', '7199.00', 2, '2014-04-27', 'productos/electrodomesticos/Aspiradora Koblenz Plata AG-1200.jpg'),
(4, 2, 'Batidora Kitchen Aid 5.6 Litros Rojo', 'Batidora Kitchen Aid KP26M1XER, herramienta fundamental en la cocina.', 'Batidora Kitchen Aid KP26M1XER, herramienta fundamental en la cocina que permite satisfacer tu creatividad. Diseñada para el uso doméstico de alto rendimiento, gracias a su cabeza elevable que te ofrece fantásticos resultados.\nCaracterísticas Generales: Batidora profesional con cabeza elevable.\nMarca: Kitchen Aid.\nModelo: KP26M1XER.\nColor y diseño: Rojo y Acero Inoxidable.\nCapacidad: 5.6 Litros.\nProgramas: 10 velocidades.\nDimensiones: Alto 41.9 cm x Ancho 27.9 cm x Profundidad 35.5 cm\nPanel de m', '8999.00', 2, '2014-04-25', 'productos/electrodomesticos/Batidora Kitchen Aid 5.6 Litros Rojo KP26M1XER.jpg'),
(5, 3, 'Anillo Calissons Diamante 0.28 Oro Blanco', 'Este flamante anillo resaltará tu belleza y elegancia en toda ocasión.', 'Este flamante anillo resaltará tu belleza y elegancia en toda ocasión.\nTipo de Producto: Anillo.\nTipo de Metal: Oro Blanco.\nQuilataje: 14K.\nTipo de Gemas: Diamante.\nPuntos Joyería: 0.28.', '12590.00', 1, '2014-04-25', 'productos/joyeria/Anillo Calissons Diamante 0.28 Oro Blanco.jpg'),
(6, 3, 'Anillo Calissons Diamante 1.00 Oro Blanco', 'Elegancia y sofisticación es lo que define a este anillo.', 'Elegancia y sofisticación es lo que define a este anillo.\nTipo de Producto: Anillo.\nTipo de Metal: Oro Blanco.\nQuilataje: 14K.\nTipo de Gemas: Diamante.\nPuntos Joyería: 1.00.', '23295.00', 1, '2014-04-25', 'productos/joyeria/Anillo Calissons Diamante 1.00 Oro Blanco.jpg'),
(7, 1, 'Base Ligera FPS50 Capture Totale Christian Di', 'Suaviza, ilumina y protege tu piel con esta base de maquillaje', 'Suaviza, ilumina y protege tu piel con esta base de maquillaje, parte de la gama de productos especialmente diseñados por Dior para el cuidado de tu rostro.\n\nColor: Envase blanco.\nTipo de producto: Facial.\nIngredientes: Secale c.\nCapacidad: 40 ml.\nPresentación: Crema.\nGénero: Mujer.', '980.00', 1, '2014-04-25', 'productos/belleza/Base Ligera FPS50 Capture Totale Christian Dior 40 ml.jpg'),
(8, 1, 'Corrector para ojeras de Elizabeth Arden para', 'Cubre el área más sensible de tus ojos y oculta las imperfecciones con Elizabeth Arden.', 'Cubre el área más sensible de tus ojos y oculta las imperfecciones con Elizabeth Arden.\n\nColor: Medio.\nTipo de Producto: Facial.\nIngredientes: Fórmula de marca E. Arden.\nCapacidad: 5.5\nPresentación: Corrector.\nGénero: Mujer.', '390.00', 1, '2014-04-25', 'productos/belleza/Corrector para ojeras de Elizabeth Arden para mujer.jpg'),
(9, 1, 'Corrector para ojos Origins Plantscription Co', 'Luce siempre joven con el corrector anti-envejecimiento Origins, ideal para cubrir las ojeras.', 'Luce siempre joven con el corrector anti-envejecimiento Origins, ideal para cubrir las ojeras, además reduce la apariencia de líneas finas, arrugas y defectos al instante.\n\nColor: Envase beige.\nTipo de producto: Para ojos.\nIngredientes: Mezcla de ingredientes de alta calidad de la marca.\nCapacidad: 5 ml.\nPresentación: Corrector semi-líquido.\nGénero: Mujer.', '285.00', 1, '2014-04-25', 'productos/belleza/Corrector para ojos Origins Plantscription Concelear 03.jpg'),
(10, 1, 'M.A.C Showstopper Eye Shadow', 'Un cuarteto de sombras coordinadas que incluye: Oh My Darling, Jest', 'Un cuarteto de sombras coordinadas que incluye: Oh My Darling, Jest, Mineralism y Showstopper en terminados Veluxe Pearl, Lustre y Escarchados.', '285.00', 1, '2014-04-25', 'productos/belleza/M.A.C Showstopper Eye Shadow x4.jpg'),
(11, 1, 'Prep + Prime Eye', 'Acondicionador y base para los párpados.', 'Acondicionador y base para los párpados. Crema con color de textura \nligera que prepara los párpados para el maquillaje. Neutraliza el \ncolor de los párpados y suaviza la piel. Permite un mejor acabado y\nduración del maquillaje de ojos. Aplicar antes de las sombras, \npigmentos y correctores. Contenido 5g.', '255.00', 1, '2014-04-26', 'productos/belleza/Prep + Prime Eye.jpg'),
(12, 1, 'Select Sheer-Loose', 'Polvos compactos ligeros.', 'Polvos compactos ligeros.\nColor: Translúcidos.\nTipo de producto: Rostro.\nCapacidad: 8grs.\nPresentación: Polvo Compacto.\nGénero: Mujer.', '375.00', 1, '2014-04-26', 'productos/belleza/Select Sheer-Loose.jpg'),
(13, 1, 'Select Sheer-Loose', 'Base de maquillaje en crema.', 'Color: Proporciona un acabado natural, ligeramente mate debido a los polvos.\nTipo de producto: Rostro.\nIngredientes: Contiene difusores ópticos que suavizan las líneas de expresión y consiguen un aspecto fresco y perfecto.\nCapacidad: 10 gm.\nPresentación: Base de Maquillaje.\nGénero: Mujer.', '485.00', 1, '2014-04-26', 'productos/belleza/Studio Tech Foundation.jpg'),
(14, 2, 'Cafetera Syntia Saeco Philips 1.2 Lt HD8837/4', 'Disfruta del placer de un café espresso como a ti de agrade desde la comodidad de tu casa.', 'Disfruta del placer de un café espresso como a ti de agrade desde la comodidad de tu casa.\nCaracterísticas generales: Cafetera Syntia espresso automática con espumador de leche clásico, la auténtica perfección del café italiano, ajuste de bebidas a su gusto y limpieza y mantenimiento sencillo.\nMarca: Philips.\nModelo: HD8837”47.\nColor y diseño: Acabado en acero inoxidable, tamaño compacto con materiales de primer nivel.\nSistema:Sistema de adaptación Saeco. Sistema aroma: preparación previa. Las combinaciones diferentes de café requieren niveles diferentes de granularidad para desplegar todo el sabor. La granularidad de molido de esta cafetera espresso puede ajustarse en 5 posiciones, desde el molido más fino para un espresso con cuerpo, hasta el más grueso para un café crème más liviano.\nCapacidad: Capacidad de granos de café: 250 g. Capacidad del recipiente para café: 8 tazas. Capacidad de almacenamiento de agua: 1.2 Lt.\nProgramas: Función de memoria para ajustar la cantidad de café, l', '19799.00', 10, '2014-04-26', 'productos/electrodomesticos/Cafetera Syntia Saeco Philips 1.2 Lt HD8837-47.jpg'),
(15, 2, 'Cafeteria Nespresso Gran Maestria Titanium', 'Gran Maestria es lo último en lujo y comodidad. Cuenta con una zona para calentar tazas y un Aerocci', 'Gran Maestria es lo último en lujo y comodidad. Cuenta con una zona para calentar tazas y un Aeroccino de última generación\n\nCaracterísticas Generales: Maquina de Café.\nCapacidad de bomba: 19 Bares.\nColor y diseño: Silver.\nSistema:Termobloc, calienta el café a 86° -3°+ 3.\nCapacidad recipiente recolector de capsulas: 14.\nTiempo de encendido: 25.\nProgramas: Espresso - Lungo.\nModo ahorro de energia: Si.\nDimensiones: 45 alto X 36 ancho X 36 fondo cm.\nComplementos: Memoria en el tamaño de taza.\nAccesorio: Si, Aeroccino espumador de leche.\nMantenimiento: Descalsificación (En el hogar).\nPotencia: 1900 W.\nConsumo de energía:29 kWh.', '9489.00', 10, '2014-04-26', 'productos/electrodomesticos/Cafeteria Nespresso Gran Maestria Titanium.jpg'),
(16, 2, 'Horno de Microondas Monogram', 'Cocina y calienta tus alimentos de manera fácil y práctica con este Horno de Microondas Monogram ZE2', 'Cocina y calienta tus alimentos de manera fácil y práctica con este Horno de Microondas Monogram ZE2160SF.\n\nCaracterísticas generales: Horno de Microondas .\nMarca: Monogram.\nModelo: ZE2160SF.\nCapacidad: 24 Pulgadas.\nColor y diseño: Acero Inoxidable.\nNiveles de programación: 10 programas.\nPanel de mando: Touch Electrónico .\nPotencia: 1200 W.', '10699.00', 10, '2014-04-26', 'productos/electrodomesticos/Horno de Microondas Monogram 24 Pulgadas Acero Inoxidable ZE2160SF.jpg'),
(17, 2, 'Moulinex Facilite Plus 6 Vel.', 'Prepara jugos, licuados y más en un minuto con Moulinex Plus.', 'Prepara jugos, licuados y más en un minuto con Moulinex Plus\n\nCaracterísticas Generales: Vaso graduado de plástico.\nMarca: Moulinex.\nModelo: LM0400C6.\nColor y diseño: Blanco.\nSistema: Sistema de seguridad para colocar el vaso.\nCapacidad: 1.5 Litros.\nProgramas: 6 velocidades más pulso.\nDimensiones: Altura 31.2 cm X Ancho 17 cm X Profundidad 27.5 cm.\nPanel de mando: Botones de pulso.\nPotencia: 500 Watss.\nEquipamiento interior: Cuchilla removibles de acero inoxidable.', '476.00', 10, '2014-04-26', 'productos/electrodomesticos/Moulinex Facilite Plus 6 Velocidades.jpg'),
(18, 2, 'Plancha Oster GCSTSP6104-013', 'Plancha Oster para planchar de una manera más fácil y rápido.', 'Plancha Oster para planchar de una manera más fácil y rápido.\n\nCaracterísticas Generales: Plancha con anti-goteo.\nMarca: Oster.\nModelo: GCSTSP6104-013.\nCapacidad: 280 ml.\nColor y diseño: Negro.\nPanel de mando: Botones.\nFunciones especiales: Apagado automático de 3 posiciones para seguridad adicional.', '400.00', 10, '2014-04-26', 'productos/electrodomesticos/Plancha Oster GCSTSP6104-013.jpg'),
(19, 2, 'Sandwichera - Wafflera Oster', 'Sandwichera y wafflera Oster, una gran idea para hacer de tus desayunos ricos y prácticos.', 'Sandwichera y wafflera Oster, una gran idea para hacer de tus desayunos ricos y prácticos.\n\nCaracterísticas: Sandwichera y Waflera bifunción.\nColor y diseño: Negro con diseño compacto.\nCapacidad: 2 porciones.\nSistema de seguridad: Auto apagado, broche de seguridad y asas frías al tacto.\nPanel de mando: Luces indicadoras.\nIncluye: Platos para waffle y platos para sandwich precortados en triángulos.', '638.00', 10, '2014-04-26', 'productos/electrodomesticos/Sandwichera - Wafflera Oster.jpg'),
(20, 3, 'Aretes Calissons Diamante 0.46 Oro Blanco', 'Esta pieza de joyería te hará lucir sensacional en toda ocasión.', 'Esta pieza de joyería te hará lucir sensacional en toda ocasión.\n\nTipo de Producto: Aretes.\nTipo de Metal: Oro Blanco.\nQuilataje: 14K.\nTipo de Gemas: Diamante.\nPuntos Joyería: 0.46.', '21995.00', 1, '2014-04-26', 'productos/joyeria/Aretes Calissons Diamante 0.46 Oro Blanco.jpg'),
(21, 3, 'Brazalete para Dama Guess, Modelo UBB71208', 'Guess tiene este padrísimo brazalete para darle el útimo toque a tu vestimenta diseñado exclusivamen', 'Guess tiene este padrísimo brazalete para darle el útimo toque a tu vestimenta diseñado exclusivamente para ti.\n\nDetalles: Brazalete rígido plateado con cristales de swarovski, esmalte color negro y cierre de imán.\nColor de metal: Plateado.\nPresentación: Brazalete.\nColor de piedras: Blanco.\nEstilo: Fino.\nNúmero de piezas: 1.\nModelo: UBB71208.\nInstrucciones de cuidado: Limpiar con un paño húmedo y líquido especial para metales.', '2199.00', 1, '2014-04-26', 'productos/joyeria/Brazalete para Dama Guess, Modelo UBB71208.jpg'),
(22, 3, 'Collar Armor Negro Swarovski', 'Luce esta hermosa pieza de joyería, que te hará ver fantástica en cualquier ocasión.', 'Luce esta hermosa pieza de joyería, que te hará ver fantástica en cualquier ocasión.\n\nTipo de Producto: Collar.\nMarca: Swarovski.\nModelo: Armor 5032831.\nMaterial: Baño de Rodio.\nAcabado: Plateado.\nColor: Plata y Negro.\nAditamentos: Cristal.\nTalla: Unitalla.\nGénero: Dama.\nNúmero de Piezas: 1.\nColección: Primavera-Verano 2014.', '3715.00', 1, '2014-04-26', 'productos/joyeria/Collar Armor Negro Swarovski.jpg'),
(23, 3, 'Esclava para Niños Roca Figaro 0x1 de 14K', 'Regala a tus niños esta linda esclava Roca Figaro de oro de 14K y demuestra cuanto los quieres.', 'Regala a tus niños esta linda esclava Roca Figaro de oro de 14K y demuestra cuanto los quieres.\n\nTipo de metal: Oro.\nColor del metal: Amarillo.\nNúmero de piezas: 1.', '3999.00', 1, '2014-04-26', 'productos/joyeria/Esclava para Niños Roca Figaro 0x1 de 14K.jpg'),
(24, 3, 'Pulsera Calissons Diamante 0.57 Oro Blanco', 'Sé el centro de atención con esta elegante pulsera hecha especialmente para ti.', 'Sé el centro de atención con esta elegante pulsera hecha especialmente para ti.\n\nTipo de Producto: Pulsera.\nTipo de Metal: Oro Blanco.\nQuilataje: 14K.\nTipo de Gemas: Diamante.\nPuntos Joyería: 0.57.', '24675.00', 1, '2014-04-26', 'productos/joyeria/Pulsera Calissons Diamante 0.57 Oro Blanco.jpg'),
(25, 4, 'En el Corazón de los Fiordos', 'Este libro te trasladara hasta tierras nórdicas para desenterrar un sombrío pasado, descúbrelo.', 'Este libro te trasladara hasta tierras nórdicas para desenterrar un sombrío pasado, descúbrelo.\nGénero: Novela Histórica.\nSubgénero: Narración.\nEdad recomendada: 18 años en adelante.\nNúmero de páginas: 544.\nIdioma: Español .\nFormato: Rústico.\nFecha en que salió a la venta: 2013.\nFecha de publicación: 2013.\nAutor: Christine Kabus.', '300.00', 1, '2014-04-27', 'productos/libros/En el Corazón de los Fiordos.jpg'),
(26, 4, 'La Canción de los Maoríes', 'Preciosa novela que nos traslada continuamente entre el tiempo de la posguerra y la actualidad.', 'Preciosa novela que nos traslada continuamente entre el tiempo de la posguerra y la actualidad.\n\nGénero: Literatura.\nSubgénero: Narrativo.\nEdad Recomendada: 25 años en adelante.\nPáginas: 703.\nIdioma: Español.\nFormato: Rústico.\nFecha en que salió a la venta: 2012.\nFecha de publicación: 2012.\nAutor: Sarah Lark.', '360.00', 1, '2014-04-26', 'productos/libros/La Canción de los Maoríes.jpg'),
(27, 4, 'La Última Reina', 'Descubre la trágica vida que llevó la reina Juana.', 'Descubre la trágica vida que llevó la reina Juana.\n\nGénero: Literatura.\nSubgénero: Histórica.\nEdad Recomendada: 20 años en adelante.\nPáginas: 432.\nIdioma: Español.\nFormato: Tapa Dura.\nFecha en que salió a la venta: 2011.\nFecha de publicación: 2011.\nAutor: C. W. Gortner.', '300.00', 1, '2014-04-26', 'productos/libros/La Última Reina.jpg'),
(28, 4, 'Triste Corazón Oscuro', 'En Triste Corazón Oscuro, las gemelas Rebecca y Hephziba soportan los maltratos de su padre.', 'En Triste Corazón Oscuro, las gemelas Rebecca y Hephziba soportan los maltratos de su padre, un pastor a quien todo el pueblo respeta hasta que se descubren sus perversidades. Entérate de la historia completa que hace un cautivador recorrido entre la inocencia y la muerte.\n\nGénero: Novela.\nSubgénero: Novela realista.\nEdad recomendada: 16 años en adelante.\nPáginas: 312.\nIdioma: Español.\nFormato: Rústico.\nFecha en que salió a la venta: 2013.\nFecha de publicación: 2013.\nAutor: Louisa Reid.', '230.00', 1, '2014-04-26', 'productos/libros/Triste Corazón Oscuro.jpg'),
(29, 4, 'Un Lugar para Refugiarse', 'Historia de novela rosa que esconde una realidad más dura de alcoholismo y malos tratos.', 'Historia de novela rosa que esconde una realidad más dura de alcoholismo y malos tratos.\n\nGénero: Literatura.\nSubgénero: Novela.\nEdad recomendada: 25 años en adelante.\nPáginas: 360.\nIdioma: Español.\nFormato: Rústico.\nFecha en que salió a la venta: 2013.\nFecha de publicación: 2013.\nAutor: Nicholas Sparks.', '249.00', 1, '2014-04-26', 'productos/libros/Un Lugar para Refugiarse.jpg'),
(30, 4, 'Una Pasión Diferente', 'El libro se desarrolla en un entorno estudiantil, de la Universidad Complutense de Madrid y de Alcal', 'El libro se desarrolla en un entorno estudiantil, de la Universidad Complutense de Madrid y de Alcalá de Henares, se deslizan amor, amistad e historia. Después de finalizar su carrera, Ana María llega becada a España. Allí conoce a Diego, quien ha vivido la sinrazón del terrorismo. Entre Diego y Ana María surge una relación poderosa y dividida. Pero más allá de cualquier sentimiento amoroso que pueda experimentar la protagonista, subyace una pasión diferente, independiente, que va en crecimiento.\n\nGénero: Literatura iberoamericana.\nSubgénero: Historia.\nEdad recomendada: 18 en adelante.\nIdioma: Español.\nFormato: Tapa blanda.\nAutor: Ximena Rubio del Valle.', '220.00', 1, '2014-04-26', 'productos/libros/Una Pasión Diferente.jpg'),
(31, 5, 'Abrigo para Dama Roberto Verino, Modelo 17132', 'Elegancia y estilo en todo momento con este abrigo que Roberto Verino trae para ti.', 'Elegancia y estilo en todo momento con este abrigo que Roberto Verino trae para ti.\nDetalles: Abrigo liso, manga larga, bolsillos y abotonado frontal, presillas en cintura, cinta de amarre, jareta abotonada en hombro, incrustraciones metálicas frontales y traseras.\nComposición: Poliéster.\nCuello: Camisero.\nEstilo: Casual.\nNúmero de piezas: 1.\nModelo: 1713238943.\nInstrucciones de lavado: En seco.', '4969.00', 1, '2014-04-26', 'productos/moda/Abrigo para Dama Roberto Verino, Modelo 1713238943.jpg'),
(32, 5, 'Blusa para Dama Soy, Modelo Bl03643', 'Luce espectacular con esta linda blusa que Soy ha diseñado exclusivamente para ti.', 'Luce espectacular con esta linda blusa que Soy ha diseñado exclusivamente para ti.\nDetalles: Blusa manga corta y calado.\nComposición: Poliéster.\nEstilo: Casual.\nCuello: Redondo.\nNúmero de piezas: 1.\nModelo: BL03643.\nIntrucciones de lavado: A mano o máquina sin blanqueador, secar a la sombra.', '471.00', 1, '2014-04-26', 'productos/moda/Blusa para Dama Soy, Modelo Bl03643.jpg'),
(33, 5, 'Bolsa para Dama Guess, Modelo VG453819', 'Guess tiene esta padrísima bolsa para llevar lo necesario y lucirla con tu vestimenta diseñado exclu', 'Guess tiene esta padrísima bolsa para llevar lo necesario y lucirla con tu vestimenta diseñado exclusivamente para ti.\n\nDetalles: Bolsa flat.\nComposición: PVC.\nEstilo: Vestir.\nTipo de cierre: Cremallera.\nNúmero de compartimentos: Varios.\nNúmero de piezas: 1.\nModelo: VG453819.\nInstrucciones de cuidado: Limpiar con un paño semi- húmedo.', '1590.00', 1, '2014-04-26', 'productos/moda/Bolsa para Dama Guess, Modelo VG453819.jpg'),
(34, 5, 'Pantalón para caballero Levi´s, Modelo 514 Sl', 'Luce un estilo casual y muy cómodo con este bonito pantalón Levi´s, combinará perfecto con tu look.', 'Luce un estilo casual y muy cómodo con este bonito pantalón Levi´s, combinará perfecto con tu look.\n\nDetalles: Pantalón liso, corte recto, bolsillos al frente, dos bolsillos traseros, cierre con cremallera y botón.\nComposición: Algodón.\nEstilo: Casual.\nNúmero de piezas: 1.\nModelo: 514 Slim Straight.\nInstrucciones de lavado: A máquina o a mano, con agua fría, secar colgado, usar plancha tibia, no usar blanqueador.', '729.00', 1, '2014-04-26', 'productos/moda/Pantalón para caballero Levi´s, Modelo 514 Slim Straight.jpg'),
(35, 5, 'Pantalón para Dama Levi´s, Modelo 115180069', 'Luce sensacional con este padrísimo pantalón que Levi´s, ha diseñado especialmente para ti.', 'Luce sensacional con este padrísimo pantalón que Levi´s, ha diseñado especialmente para ti.\n\nDetalles: Pantalón recto, corte a la cadera, diseño liso, bolsillos, cremallera con botón, pretina con presillas.\nComposición: 83% Algodón, 1% Elastano, 16% Poliéster.\nEstilo: Casual.\nNúmero de piezas: 1.\nModelo: 115180069.\nInstrucciones de Lavado: A mano o máquina en ciclo delicado, agua fría o tibia, no usar blanqueador, secar colgado.', '729.00', 1, '2014-04-26', 'productos/moda/Pantalón para Dama Levi´s, Modelo 115180069.jpg'),
(36, 5, 'Playera para Caballero Calvin Klein, Modelo 4', 'Conserva tu estilo casual, con esta bonita playera que Calvin Klein ha traído en exclusiva para ti.', 'Conserva tu estilo casual, con esta bonita playera que Calvin Klein ha traído en exclusiva para ti.\n\nDetalles: Playera corte recto, manga corta.\nComposición: Algodón.\nCuello: Redondo.\nEstilo: Casual.\nNúmero de piezas: 1.\nModelo: 41SK257.\nInstrucciones de lavado: A máquina, con agua fría, no usar blanqueador.', '595.00', 1, '2014-04-26', 'productos/moda/Playera para Caballero Calvin Klein, Modelo 41SK257.jpg'),
(37, 5, '', '', '', '0.00', 1, '2014-04-26', 'productos/moda/.jpg'),
(38, 5, 'Traje para caballero JBE 53149 liso', 'Luce un estilo único y elegante con este increíble traje que JBE ha diseñado para ti.', 'Luce un estilo único y elegante con este increíble traje que JBE ha diseñado para ti.\n\nDetalles: Saco de manga larga liso con 2 botones, 2 bolsillos al frente y 1 bolsillo en la parte superior. Pantalón liso con 2 bolsillos al frente.\nComposición: Lana.\nEstilo del cuello: V.\nNúmero de piezas: 2.\nModelo: 53149.', '1990.00', 1, '2014-04-26', 'productos/moda/Traje para caballero JBE 53149 liso.jpg'),
(39, 5, 'Vestido para Dama Guess, Modelo W41K47K2Y00', 'Sensual y atractiva con este fantástico vestido que Guess trae para ti.', 'Sensual y atractiva con este fantástico vestido que Guess trae para ti.\n\nDetalles: Vestido entablado a rayas, corto, manga 3/4, cinta decorativa en cintura.\nComposición: Rayón.\nCuello: En V.\nEstilo: Casual.\nNúmero de piezas: 1.\nModelo: W41K47K2Y00.\nInstrucciones de lavado: A mano o a máquina con agua fría, no usar blanqueador, no exprimir ni centrifugar, secar colgado a la sombra, planchar temperatura ', '1490.00', 1, '2014-04-26', 'productos/moda/Vestido para Dama Guess, Modelo W41K47K2Y00.jpg'),
(40, 5, 'Zapatilla para Dama Tommy Hilfiger, Modelo FW', 'Siente la comodidad de estas hermosas zapatillas Tommy Hilfiger, que por su diseño te aporta equilib', 'Siente la comodidad de estas hermosas zapatillas Tommy Hilfiger, que por su diseño te aporta equilibrio y seguridad al caminar.\n\nDetalles: Zapatilla con plataforma, acabado en piel, Iniciales de la firma de metal en el talón, forro de tela con estampado de máquina de escribir, altura del tacón con tira en distinto color.\nComposición: Piel, suela de goma.\nEstilo: Vestir.\nNúmero de piezas: 2 (1 par).\nModelo: FW56815931990.\nInstrucciones de cuidado: Limpiar con un paño húmedo o crema especial para piel.', '1679.00', 1, '2014-04-26', 'productos/moda/Zapatilla para Dama Tommy Hilfiger, Modelo FW568159319.jpg'),
(41, 5, 'Zapato para caballero JBE 1216-1 casual', 'Realza tu estilo casual y de buen gusto con este cómodo par de zapatos que JBE, trae especialmente p', 'Realza tu estilo casual y de buen gusto con este cómodo par de zapatos que JBE, trae especialmente para ti.\n\nDetalles: Zapato con costura en contraste y suela sintética.\nComposición: Piel.\nEstilo: Casual.\nNúmero de piezas: 2.\nModelo: 1216-1.', '499.00', 1, '2014-04-26', 'productos/moda/Zapato para caballero JBE 1216-1 casual.jpg'),
(42, 6, '20 Grandes Exitos Laura Pausini 2 CDS', 'Los más grandes éxitos de Laura Pausini en una compilación adquiérelo y forma tu colección.', 'Los más grandes éxitos de Laura Pausini en una compilación adquiérelo y forma tu colección.\n\nEstudio: Sony Music.\nInterprete: Laura Pausini.\nAño de Lanzamiento: 2013.\nGénero: Pop.\nFormato: CD.\nOrigen: Nacional.', '215.00', 1, '2014-04-26', 'productos/musica/20 Grandes Exitos Laura Pausini 2 CDS.jpg'),
(43, 6, 'Alejandro Fernández 15 Años de Éxitos CD + DV', '15 Años de éxitos un disco con el exitoso Alejandro Fernández no te lo puedes perder.', '15 Años de éxitos un disco con el exitoso Alejandro Fernández no te lo puedes perder.\n\nNombre del CD: 15 Años de éxitos.\nArtista o grupo: Alejandro Fernández.\n1. Me dediqué a perderte.\n2. Qué voy a hacer con mi amor.\n3. Qué lástima.\n4. Canta corazón.\n5. No sé olvidar.\n6. Si tú supieras.\n7. Niña amada mía.\n8. Si tú no vuelves.\n9. Tantita pena.\n10. Si he sabido amor.\n11. Loco.\n12. Abrázame.\n13. Nube viajera.\n14. Como quien pierde una estrella.\n15. Piel de niña.\n16. El lado oscuro del amor.\nAño: 2007.\nIncluye: CD + DVD', '199.00', 1, '2014-04-26', 'productos/musica/Alejandro Fernández 15 Años de Éxitos CD + DVD.jpg'),
(44, 6, 'Essential Great Voices II', 'Si eres amante de la música, este disco no podrá faltar en tu colección.', 'Si eres amante de la música, este disco no podrá faltar en tu colección.\n\nNombre del CD: Essential Great Voices II.\nArtistas: Varios.\nLista de Canciones:\nRegresa a mí\nPapa can you hear me?.\nArrivederci Roma.\nMorgen! op.\nBecause we believe.\nI dreamed a dream.\nIl volo Marcelo Álvarez.\nMusic of the night.\nEl óndor pasa.\nEternally.\nI wish.\nCanto alla vita.\nLa sonnambula: ah! non credea mirarti... ah! non giunge ” moderation.\nSevila.', '299.00', 1, '2014-04-26', 'productos/musica/Essential Great Voices II.jpg'),
(45, 6, 'José Alfredo Jiménez Canta sus Canciones con ', 'Dale un toque actual a los temas de Jóse Alfredo Jiménez con la Banda Sinaloense El recodo De Cruz L', 'Dale un toque actual a los temas de Jóse Alfredo Jiménez con la Banda Sinaloense El recodo De Cruz Lizárraga.\n\nEstudio: Sony Music.\nInterprete: José Alfredo Jiménez.\nAño de Lanzamiento: 1994.\nGénero: Regional Mexicano.\nFormato: CD.\nOrigen: Nacional.\nIdioma: Español.', '135.00', 1, '2014-04-26', 'productos/musica/José Alfredo Jiménez Canta sus Canciones con la Banda Sinaloense de Cruz Lizárraga CD.jpg'),
(46, 6, 'Marc Anthony 3.0 CD', 'La súper estrella de la música Marc Anthony regresa a los escenarios con este fenomenal disco 3.0 co', 'La súper estrella de la música Marc Anthony regresa a los escenarios con este fenomenal disco 3.0 con 10 románticos temas que te harán suspira.\n\nEstudio: Sony Music.\nIntérprete: Marc Anthony.\nAño de lanzamiento: 2013.\nGénero: Pop.\nFormato: CD.\nOrigen: Nacional.\nIdioma: Español.', '169.00', 1, '2014-04-26', 'productos/musica/Marc Anthony 3.0 CD.jpg'),
(47, 6, 'Twilight Forever Love Song 2 CD', 'Revive la Fantástica saga de Crepusculo con este increíble CD.', 'Revive la Fantástica saga de Crepusculo con este increíble CD.\n\nEstudio: Warner.\nInterprete: Varios.\nGénero: Soundtrack.\nAño de Lanzamiento: 2014.\nFormato: CD.\nOrigen: Importado.', '219.00', 1, '2014-04-26', 'productos/musica/Twilight Forever Love Song 2 CD.jpg'),
(48, 6, 'Whitney Houston I Will Al Ways Love You The B', 'Disfruta de la grandiosa voz de Whitney Houston en este excelente disco doble.', 'Disfruta de la grandiosa voz de Whitney Houston en este excelente disco doble.\n\nEstudio: Sony Music.\nIntérprete: Whitney Houston.\nAño de lanzamiento: 2012.\nGénero: Pop.\nFormato: 2 CD.\nOrigen: Nacional.\nIdioma: Inglés.', '239.00', 1, '2014-04-26', 'productos/musica/Whitney Houston I Will Al Ways Love You The Best 2 CD.jpg'),
(49, 7, '2 Sillas Gel B Trendy Gris Plástico', '', 'Color: Gris.\nEstilo: Trendy.\nMaterial: Plástico.\nNúmero de Piezas: 2.\nMedidas: Alto 85 cm x Ancho 42 cm x Profundiad 42 cm.\nInstrucciones de uso y mantenimiento: Limpiar con paño seco. No usar abrasivos.', '5499.00', 1, '2014-04-26', 'productos/oficina/2 Sillas Gel B Trendy Gris Plástico.jpg'),
(50, 7, 'Bar Hari Haus Contemporáneo Color Café', 'Vanguardia y estilo, es lo que ofrecemos para ti con este novedoso diseño.', 'Vanguardia y estilo, es lo que ofrecemos para ti con este novedoso diseño.\n\nEstilo: Contemporáneo.\nMaterial: Madera.\nMedidas: Alto 120 cm x Ancho 60 cm x Profundidad 41 cm aprox.\nColor: Café.\nNo. de piezas: 1.\nComponente principal: Madera de mango y Rattán.\nRecomendaciones de cuidado: Limpiar con un paño seco, no usar abrasivos, dar mantenimiento cada 6 meses con aceite de linaza o teca.', '6299.00', 1, '2014-04-26', 'productos/oficina/Bar Hari Haus Contemporáneo Color Café.jpg'),
(51, 7, 'Escritorio Cheisa Moderno Color Chocolate', 'Te ofrecemos los mejores diseños para dar elegancia y estilo al interior de tu hogar.', 'Te ofrecemos los mejores diseños para dar elegancia y estilo al interior de tu hogar.\n\nEstilo: Moderno.\nMaterial: Madera.\nMedidas: Alto 80 cm x Ancho 180 cm x Profundidad 70 cm aprox.\nColor: Chocolate.\nNo. de piezas: 1.\nComponente principal: Madera de álamo americano, Okumé.\nAcabados especiales: Acabado poliuretano patinado semi-mate.\nHerrajes: Correderas de acero y jaladeras de acero inoxidable.\nRecomendaciones de cuidado: Limpiar con un paño seco, no usar abrasivos.', '17999.00', 1, '2014-04-26', 'productos/oficina/Escritorio Cheisa Moderno Color Chocolate.jpg'),
(52, 7, 'Escritorio Portugal Samu Clásico', 'Excelente Escritorio Portugal para darle un estilo elegante a tu estudio.', 'Excelente Escritorio Portugal para darle un estilo elegante a tu estudio.\n\nColor: Nogal.\nEstilo: Clásico.\nMaterial: MDF.\nNúmero de piezas: 1.\nMedidas: Alto 80 cm x Ancho 181 cm x Profundidad 83 cm.\nHerrajes: Jaladeras metálicas.\nAccesorios Incluidos: 7 Cajones.\nInstrucciones de uso y mantenimiento: Limpiar ocasionalmente con un paño húmedo, no usar abrasivos.', '10000.00', 1, '2014-04-26', 'productos/oficina/Escritorio Portugal Samu Clásico Nogal.jpg'),
(53, 7, 'Librero Weston Amoni', 'Excelente Librero Weston de elegante diseño.', 'Excelente Librero Weston de elegante diseño.\n\nColor: Caoba.\nEstilo: Contemporáneo.\nMaterial: MDF.\nNúmero de Piezas: 1.\nMedidas: Alto 122 cm x Ancho 120 cm x Profundidad 32 cm.\nAccesorios Incluidos: 11 repisas y 3 cajones.\nInstrucciones de uso y mantenimiento: Limpiar ocasionalmente con un paño húmedo.', '6999.00', 1, '2014-04-26', 'productos/oficina/Librero Weston Amoni Contemporáneo Caoba.jpg'),
(54, 7, 'Mesa de Juego Portugal Clásico', 'Sensacional Mesa de Juego Portugal para esas momentos únicos con los amigos.', 'Sensacional Mesa de Juego Portugal para esas momentos únicos con los amigos.\nModelo.Portugal.\nProducto: Mesa de Juego.\nColor: Natural.\nEstilo: Clásico.\nMaterial: Terminado en nogal.Tableros de MDF y aglomerado enchapados en varios espesores. Pedestal de madera.\nDimensiones: Alto 84 cm. Ancho 132 cm. y Profunidad 151 cm.\nOrigen: Nacional.\nInformación adicional: Cuenta con 6 cajones. Forma hexagonal. Cubierta de tela. Pedestal de madera.', '37999.00', 1, '2014-04-26', 'productos/oficina/Mesa de Juego Portugal Clásico.jpg'),
(55, 7, 'Mesa Picasso Trendy Vidrio/Acero', 'Disfruta de esta excelente Mesa Picasso que llenará de estilo y clase tu hogar.', 'Disfruta de esta excelente Mesa Picasso que llenará de estilo y clase tu hogar.\n\nMaterial: Base de metal cromado y superficie de cristal.\nMedidas: Alto 76 cm x Ancho 120 cm x Profundidad 76 cm.\nColor: Transparente.\nEstilo Trendy.\nRecomendaciones del cuidado: Limpiar ocasionalmente con un paño húmedo y no recargarse sobre el cristal', '13999.00', 1, '2014-04-26', 'productos/oficina/Mesa Picasso Trendy VidrioAcero.jpg'),
(56, 7, 'Silla Kodiak Trendy Blanca', 'Silla de material resistente, ideal para exteriores y de peso ligero.', 'Silla de material resistente, ideal para exteriores y de peso ligero.\n\nEstilo: Trendy.\nMaterial: Vinil.\nMedidas: Alto 80 cm x Ancho 45 cm x Profundidad 45 cm.\nColor: Blanco.\nRecomendaciones especiales: Limpiar con paño húmedo no usar abrasivos.', '2299.00', 1, '2014-04-26', 'productos/oficina/Silla Kodiak Trendy Blanca.jpg'),
(57, 7, 'Sillón Cantoni Redondo Tela', 'Sillón Cantoni con el diseño ideal para un descanso mágico.', 'Sillón Cantoni con el diseño ideal para un descanso mágico.\n\nColor: Arena.\nEstilo: Contemporáneo.\nMaterial: Tapizado en tela de Jacqard.\nMedidas: Alto 100 cm x Ancho 163 cm x Profundidad 149 cm.\nComponente principal: Madera de pino.', '12999.00', 1, '2014-04-26', 'productos/oficina/Sillón Cantoni Redondo Tela.jpg'),
(58, 7, 'Sofa Cama Shapell', 'Decora tu hogar con el estilo y elegancia que te ofrece este lindo sofá cama Shapell.', 'Decora tu hogar con el estilo y elegancia que te ofrece este lindo sofá cama Shapell.\n\nColor: Gris.\nEstilo: Contemporáneo.\nNo. de piezas: 1.\nMedidas: Alto 104 cm x Ancho 225 cm x Profundidad 92 cm.\nComponente principal: Madera de pino.\nAcabados especiales: Tapizado en tela.', '2321.00', 1, '2014-04-26', 'productos/oficina/Sofa Cama Shapell.jpg'),
(59, 8, 'Aqua Marine Fragancia para Hombre', 'La fragancia de Aqva Marine es para ti es de un estilo relajado ideal para usarlo en todo tipo de oc', 'La fragancia de Aqva Marine es para ti es de un estilo relajado ideal para usarlo en todo tipo de ocasiones.\n\nColor: Envase Transparente.\nTipo de Producto: Fragancia.\nIngredientes: Fórmula secreta de la marca Bvlgari.\nCapacidad: 150 ml.\nPresentación: Eau de Toilette.\nGénero: Hombre.\nNúmero de piezas: 1.', '1550.00', 1, '2014-04-26', 'productos/perfumes/Aqua Marine Fragancia para Hombre.jpg'),
(60, 8, 'Bright Crystal Versace Eau de Toilette 90 ml', 'Versace Bright Crystal una fragancia irresistible y brillante, creada para las mujeres más imponente', 'Versace Bright Crystal una fragancia irresistible y brillante, creada para las mujeres más imponentes.\n\nColor: Rosa.\nTipo de producto: Corporal.\nIngredientes: Granada, Magnolia y Flor de Loto, Matizado con Almizcle y Ámbar.\nCapacidad: 90 ml.\nPresentación: Fragancia.\nGénero: Dama.\nNúmero de piezas: 1.\nAroma: Dulce.', '1580.00', 1, '2014-04-26', 'productos/perfumes/Bright Crystal Versace Eau de Toilette 90 ml.jpg'),
(61, 8, 'Fragancia Be Delicious Fresh Blossom, para da', 'Lleva siempre la frescura de la primavera contigo, con este aroma lleno de energía.', 'Lleva siempre la frescura de la primavera contigo, con este aroma lleno de energía.\n\nColor: Envase transparente y plata.\nTipo de Producto: Corporal.\nIngredientes: Pétalos de rosa, albaricoque y jazmín.\nCapacidad: 30 ml.\nPresentación: Fragancia.\nGénero: Mujer.\nNúmero de piezas: 1.', '650.00', 1, '2014-04-26', 'productos/perfumes/Fragancia Be Delicious Fresh Blossom, para dama.jpg'),
(62, 8, 'Fragancia Gucci By Gucci Pour Homme EDT 90 ml', 'Fragancia Gucci By Gucci Pour Homme, la fragancia ideal para el hombre moderno, sensual y elegante.', 'Fragancia Gucci By Gucci Pour Homme, la fragancia ideal para el hombre moderno, sensual y elegante.\n\nColor: Botella transparente y tapa plateada.\nTipo de producto: Corporal.\nIngredientes: Notas altas: Bergamota, ciprés, violeta. Notas del corazón: Tabaco, Jasmine. Notas de Fondo: Pachulí, olíbano, ámbar y resina Elemi.\nCapacidad: 90 ml.\nPresentación: Fragancia.\nGénero: Hombre.\nNúmero de piezas: 1.\nAroma: Amaderado-floral.', '1360.00', 1, '2014-04-26', 'productos/perfumes/Fragancia Gucci By Gucci Pour Homme EDT 90 ml.jpg'),
(63, 8, 'Fragancia Swarovski Aura EDT de 75 ml', 'Fragancia Aura de Swarosvsky para la mujer moderna, elegante y audaz.', 'Fragancia Aura de Swarosvsky para la mujer moderna, elegante y audaz.\n\nColor: Elegante botella rosa con tapa plateada.\nTipo de producto: Corporal.\nIngredientes: Nota de salida: lichi. Notas de corazón: jazmín, nardos y rosa. Notas de fondo: almizcle, ámbar, benjuí y pimienta rosa.\nCapacidad: 75 ml.\nPresentación: Fragancia.\nGénero: Mujer.\nNúmero de piezas: 1.\nAroma: Floral.', '1250.00', 1, '2014-04-26', 'productos/perfumes/Fragancia Swarovski Aura EDT de 75 ml.jpg'),
(64, 8, 'Perfume Gucci Guilt para Caballero 75 ml', 'Fragancia Gucci Guilt, el aroma innovador que nadie podrá resistir.', 'Fragancia Gucci Guilt, el aroma innovador que nadie podrá resistir.\n\nColor: Botella transparente con tapa dorada.\nTipo de producto: Corporal.\nIngredientes: Bergamota, mora negra, azahar, cuero, patchouli y sándalo.\nCapacidad: 75 ml.\nPresentación: Fragancia.\nGénero: Hombre.\nNúmero de piezas: 1.\nAroma: Floral.', '1850.00', 1, '2014-04-26', 'productos/perfumes/Perfume Gucci Guilt para Caballero 75 ml.jpg'),
(65, 8, 'Set de Regalo Night Guess EDT 100ml', 'Dale el toque final a tu arreglo personal con este exquisito aroma que te envolverá.', 'Dale el toque final a tu arreglo personal con este exquisito aroma que te envolverá.\n\nTipo de Producto: Estuche Fragancia.\nMarca: Guess.\nArt. Proveedor: GUE201545.\nGénero: Caballero.\nCapacidad EDT (Eau de Toilette): 100 ml.\nCapacidad Desodorante Body Spray: 96 g.\nNúmero de Piezas: 2.', '1000.00', 1, '2014-04-26', 'productos/perfumes/Set de Regalo Night Guess EDT 100ml.jpg'),
(66, 8, 'Set de Regalo Seduc Homme EDT 100ml Guess', 'Adquiere este coqueto set y prepárate con el delicioso aroma de esta fragancia para cualquier situac', 'Adquiere este coqueto set y prepárate con el delicioso aroma de esta fragancia para cualquier situación.\n\nTipo de Producto: Set Fragancia.\nMarca: Guess.\nArt. Proveedor: GUE201531.\nCapacidad EDT (Eau de Toilette): 100 ml.\nCapacidad Mini-EDT: 10 ml.\nGénero: Caballero.\nNúmero de Piezas: 2.', '950.00', 1, '2014-04-26', 'productos/perfumes/Set de Regalo Seduc Homme EDT 100ml Guess.jpg'),
(67, 9, 'Blu-Ray Cambridge752BD', 'Escucha toda tu música con el nuevo reproductor 752BD de Blu-ray.', 'Escucha toda tu música con el nuevo reproductor 752BD de Blu-ray.\n\nMarca: Cambridge.\nModelo: 752BD.\nTipo de sonido: Surround.\nFormatos de reproducción: MP3, AAC, WMA, FLAC y WAV, Blu-ray 3D, Blu-ray, DVD, CD, SACD, DVD-A, AVCHD y HDCD.\nEntradas: HDMI, USB.\nSalidas: 2 salidas traseras para TV y proyector.\nEscalador a Full-HD: 1080p”ak.\nControl remoto: Sí.\nMedidas: Alto 8.5 cm x Ancho 43 cm x Profundidad 31 cm.\nPeso: 5 Kg.\nColor: Gris oscuro.\nSe conecta a la red a través de Ethernet o Wi-Fi.', '34999.00', 1, '2014-04-26', 'productos/tecnologia/Blu-Ray Cambridge752BD.jpg'),
(68, 9, 'Cámara Reflex Sony Alpha SLT-A77', 'Te ofrece una mayor calidad de imagen y mayor velocidad de disparo continuo.', 'Cámara Sony Reflex Alpha SLT-A77 te ofrece una mayor calidad de imagen y mayor velocidad de disparo continuo.\n\nMarca: Sony.\nModelo: Alpha SLT-A77.\nTipo de resolución: Digital.\nTipo de pantalla: TFT, LCD Xtra Fine con tecnología TruBlack.\nTamañno de pantalla: 3 pulgadas.\nResolución: 24.3 megapíxeles.\nFormatos de memoria compatibles: SD / SDHC / SDXC.\nConectividad: USB 2.0 de alta velocidad (almacenamiento masivo / modo MTP modo). HDMI de salida HDMI mini conector.\nFunciones: SteadyShot INSIDE estabilización de imagen). Balance de blancos. Bloqueo AE. Modos de enfoque AF de disparo simple, Auto AF, AF continuo.\nTipo de grabación: Full HD. AVCHD/MP4.\nPeso: 653 g.\nDimensiones: Alto 14.2 cm X Ancho 10.4 cm X Profundidad 10.5 cm.\nOtros: Sensibilidad Auto, ISO 100 a 16000. Batería recargable NP-FM500H.', '28799.00', 1, '2014-04-26', 'productos/tecnologia/Cámara Reflex Sony Alpha SLT-A77.jpg'),
(69, 9, 'Consola Xbox 360 250 GB + Kinect + Juegos', 'Con este nuevo accesorio de Xbox ya no es necesario tener un control en la mano, ¡Tú eres el control', 'Con este nuevo accesorio de Xbox ya no es necesario tener un control en la mano, ¡Tú eres el control! Podrás moverte libremente gracias a su sensor de movimiento. Aprovecha y ahorra con este paquete.\r\n\r\nMarca: Microsoft.\r\nModelo: Xbox 360.\r\nCapacidad de almacenamiento: 250 GB.\r\nColor: Negro.\r\nFormatos soportados: Xbox 360.\r\nEntradas y Salidas: RCA. A”V. HDMI. USB. Wi-fi integrado.\r\nIncluye: Kinect, Kinect Sports: Season Two, Kinect Adventures y Forza Horizon, 1 Control inalámbrico.', '6199.00', 10, '2014-04-27', 'productos/tecnologia/Consola Xbox 360 250 GB + Kinect + Juegos.jpg'),
(70, 9, 'Desktop Apple iMac 21.5"', 'Apple reinventa el concepto de Desktop y trae para ti su modelo ME087E"A.', 'Apple reinventa el concepto de Desktop y trae para ti su modelo ME087E"A.\r\n\r\nMarca: Apple.\r\nModelo: ME087E"A.\r\nColor: Plata.\r\nProcesador: Intel Core i5 de 2.9 GHz.\r\nMemoria RAM: 8 GB.\r\nDisco duro: 1 TB.\r\nSistema operativo: OS X Mountain Lion.\r\nTipo de pantalla: LED 21.5".\r\nResolución de pantalla: Full-HD. 1920 x 1080.', '26499.00', 6, '2014-04-26', 'productos/tecnologia/Desktop Apple iMac ME087E-A 21.5.jpg'),
(71, 9, 'iPad Apple Air Wifi 32GB Gris Obscuro', 'Nuevo diseño, hace lo imposible, pesa lo impensable. iPad Apple Air Wifi 32 GB Gris Obscuro.', 'Nuevo diseño, hace lo imposible, pesa lo impensable. iPad Apple Air Wifi 32 GB Gris Obscuro.\r\n\r\nMarca: Apple.\r\nModelo: iPad Air Wifi.\r\nColor: Gris Obscuro.\r\nProcesador: Chip A7 con arquitectura de 64 bits y coprocesador de movimiento M7.\r\nDisco duro: 32 GB.\r\nSistema operativo: iOS 7.\r\nTipo de pantalla: Retina, Multi touch retroiluminada por LED de 9.7".\r\nConectividad: Wi-Fi (802.11a”b”g”n), canal doble (2.4 GHz y 5 GHz) y MIMOTecnología Bluetooth 4.0.\r\nPeso: 469 gr.\r\nWebcam: iSightFotos de 5 MP, Autoenfoque,Detección de caras, Iluminación posterior.\r\nBateria: Integrada recargable de polímero de litio de 32.4 vatios por hora, Hasta 10 horas de navegación por Internet sobre Wi-Fi, visualización de videos o reproducción de música, Carga a través del adaptador de corriente o USB al sistema de la computadora.\r\nEntradas y salidas: Minijack de 3.5 mm para audífonos estéreo, Bocina integradaMicrófono, Conector lightning.\r\nSensores: Giroscopio de tres ejes, Acelerómetro, Sensor de luz ambiental', '9999.00', 9, '2014-04-27', 'productos/tecnologia/iPad Apple Air Wifi 32GB Gris Obscuro.jpg'),
(72, 9, 'iPod Apple Nano 16GB, Púrpura', 'Cambia el concepto de escuchar tu música con el iPod nano que APPLE trae para ti.', 'Cambia el concepto de escuchar tu música con el iPod nano que APPLE trae para ti.\r\n\r\nMarca: Apple.\r\nModelo: MD479E-A.\r\nColor: Purpura.\r\nRespuesta de frecuencia: 20 Hz a 20 GHz.\r\nSintonizador: FM.\r\nEntradas: Plug 3.5.\r\nMedidas: Alto 7.6 cm x Ancho 3.9 cm x Profundidad 0.5 cm.\r\nPeso: 31 g.\r\nCapacidad: 16 GB', '2399.00', 3, '2014-04-25', 'productos/tecnologia/iPod Apple Nano 16GB, Púrpura.jpg'),
(73, 9, 'Mouse Arc Touch Surface', 'Microsoft tiene para ti este Mouse inalámbrico especialmente para dispositivos Surface.', 'Microsoft tiene para ti este Mouse inalámbrico especialmente para dispositivos Surface.\r\n\r\nMarca: Microsoft.\r\nTipo de Accesorio: Mouse Inalambrico.\r\nModelo: 6440DD4.\r\nConexión: Bluetooth.\r\nOtros: Viene con una banda flexible que cuando la arqueamos se enciende el ratón y permite agarrarlo con una posición agradable. Si queremos apagarlo, tan sólo hay que ponerlo en posición recta.', '1199.00', 3, '2014-04-26', 'productos/tecnologia/Mouse Arc Touch Surface Microsoft, Negro.jpg'),
(74, 9, 'Multifuncional Epson L355 Negro', 'La mejor calidad para tus documentos y fotos solo con el multifuncional L210 de Epson.', 'La mejor calidad para tus documentos y fotos solo con el multifuncional L210 de Epson.\r\n\r\nMarca: Epson.\r\nModelo: L355.\r\nFunciones: Imprime, copia y escanea.\r\nTecnología de impresión: EPSON Micropiezo punto variable Impresión a 4 colores (CMYK).\r\nConexiones: USB. Wi-fi.\r\nTipo de escáner: Escaner a color de cama plana.\r\nSistemas operativos compatibles: Windows XP, XP Professional 64 bits, Vista, 7. Mac OS 10.5.8 - 10.8.\r\nAccesorios incluidos: Cable de alimentación. Cable USB. CD con drivers. Software OCR.\r\nMedidas: Alto 14.5 cm x Ancho 47.2 cm x Profundidad 30 cm.', '3999.00', 4, '2014-04-26', 'productos/tecnologia/Multifuncional Epson L355 Negro.jpg'),
(75, 9, 'Pantalla LED Sharp LC70UD1U 70"', 'Una excelente calidad de imagen en tu hogar con esta pantalla Sharp.\r\n', 'Marca: Sharp.\r\nModelo: LC70UD1U.\r\nTipo de Pantalla: LCD.\r\nTamaño de Pantalla: 70".\r\nResolición: Ultra HD 3840X2160.\r\nTipo de Sonido: 10W +10W+ 15W (w”Subwoofer)\r\nCalidad en Movimiento en HZ: 120 HZ.\r\nNúmero de Bocinas: 2.\r\nColor: Negro.\r\nMarco: Plástico.\r\nTipo de Base: Fija.\r\nEntradas: 4 HDMI, 1 video compuesto, 1 video componentes HD, 1 PC, 2 USB\r\nSalidas: 2 Audio\r\nPeso: 54 kg.\r\nMedidas: Alto 99.6 cm x Ancho 157.8 cm x Profundidad 6.4 cm.', '94999.00', 4, '2014-04-26', 'productos/tecnologia/Pantalla LED Sharp LC70UD1U 70.jpg'),
(76, 9, 'Sony Xperia Z Ultra Negro Telcel', 'Vive todo con la mejor tecnología que Sony Xperia tiene para ti.', 'Vive todo con la mejor tecnología que Sony Xperia tiene para ti.\r\n\r\nSistema Operativo: Android OS, v4.2 (Jelly Bean), v4.3.\r\nVelocidad del navegador: 1 GHz.\r\nTipo de conexiones: WiFi, Bluetooth, USB 2.0.\r\nMemoria interna: 16 GB.\r\nMemoria RAM: 2 GB.\r\nTipo de pantalla: Capacitive touchscreen, 16M colors.\r\nTamaño de pantalla: 6.4 pulgadas.\r\nCámara: Si.\r\nPíxeles de cámara: 8 megapíxeles.\r\nVideocámara: 1080p@30fps, video stabilization, HDR.\r\nColor: Negro.\r\nFormatos de reproducción de música: MP3, 3GPP, MP4, SMF, WAV, OTA y Ogg vorbis.\r\nMedidas: Alto 17.9 cm x Ancho 9.2 cm x Profundidad 0.65 cm.\r\nRegión: Telcel solo DF.\r\nLimitado a Existencias.', '10549.00', 14, '2014-04-27', 'productos/tecnologia/Sony Xperia Z Ultra Negro Telcel.jpg'),
(77, 10, 'Brandy Torres 20 Años botella de 700 ml', 'Para los conocedores con estilo, Te traemos Brandy Torres 20 años.', 'Para los conocedores con estilo, Te traemos Brandy Torres 20 años.\n\nTipo de vino: Brandy.\nGrados de alcohol: 40 %.\nContenido: 700 ml.\nCrianza: Con el paso de los años, en las barricas de roble americano, se funden, en íntima armonía, los elegantes y grasos matices del roble con el intenso y espirituoso aroma de las venerables holandas que dan carácter al Torres 10, Gran Reserva.\nDetalles: 100% uva.\nPaís de origen: España.\nPresentación: Botella.', '665.00', 1, '2014-04-26', 'productos/vinos/Brandy Torres 20 Años 700 ml.jpg'),
(78, 10, 'Champagne Dom Perignon Oenotheque .750', 'Dom Pérignon Oenotheque 1996 está elaborado con uvas Chardonnay y Pinot Noir Gran Cru. ¿Viene en una', 'Dom Pérignon Oenotheque 1996 está elaborado con uvas Chardonnay y Pinot Noir Gran Cru. ¿Viene en una botella negra impresionante.\n\nTipo de bebida: Vino Espumoso.\nVolumen de alcohol: 12.5%.\nContenido: 750 ml.\nPaís de origen: Francia.\nPresentación: Botella.\nMaridaje: Platos, Marisco, Langosta.\nTipo de uva: Chardonnay y Pinot Noir Gran Cru.', '5870.00', 1, '2014-04-26', 'productos/vinos/Champagne Dom Perignon Oenotheque .750.jpg'),
(79, 10, 'Cognac Richard Hennessy botella de 700 ml', 'Disfruta del peculiar sabor del Cognac Richard Hennessy', 'Disfruta del peculiar sabor del Cognac Richard Hennessy\n\nTipo de vino: Cognac.\nGrados de alcohol: Volumen 40 %.\nContenido: 700 ml.\nPresentación: Botella.', '71490.00', 1, '2014-04-26', 'productos/vinos/Cognac Richard Hennessy 700 ml.jpg'),
(80, 10, 'Ginebra Hendricks 750 ml', 'Disfruta degustando este delicioso Ginebra para ocasiones especiales.', 'Disfruta degustando este delicioso Ginebra para ocasiones especiales.\n\nTipo de bebida: Ginebra.\nGrados de alcohol: 44%.\nContenido: 750 ml.\nCrianza: 100% Cebada.\nPaís de origen: Escocia.\nTítulo: Ginebra Hendricks 750 ml.\nMarca: Hendricks\nSólo para mayores de 18 años. Evita el exceso.', '512.00', 1, '2014-04-26', 'productos/vinos/Ginebra Hendricks 750 ml.jpg'),
(81, 10, 'Tequila Herencia Historica 27 de Mayo 750 ml', 'Verificado y certificado oficialmente por el Consejo Regulador como ingrediente mexicano, para crear', 'Verificado y certificado oficialmente por el Consejo Regulador como ingrediente mexicano, para crear una nueva amalgama de sabores de tradición. Tequila 100% de Agave Azul de una suavidad en sabor y aroma nunca antes obtenidos en una bebida.\n\nTipo de bebida: Tequila.\nContenido: 750 ml.\nVolumen de alcohol: 38%.\nCrianza: Herencia Histórico es extremadamente suave con delicados toques de aromas de pasas bastante sorprendente teniendo un carácter agave agradable. Sin duda, un Tequila único, pero suave y perfectamente equilibrado. El olor recuerda a frutas exóticas, almendras y semillas de albaricoque, maderas ricas, intensas y poderosas. El sabor es muy suave y cremoso, redondo, duro, muy elegante, con aromas de los frutos secos, el jerez, la vainilla y la miel, con un fino toque de madera, tierra y muy ligeramente ahumado. El sabor después es muy largo, seco y dulce, notable nada parecido se puede obtener de nuevo.\nDetalles: Tequila Herencia Historico conmemora la fecha de mayo 27 de 1997', '5100.00', 1, '2014-04-26', 'productos/vinos/Tequila Herencia Historica 27 de Mayo 750 ml.jpg');
INSERT INTO `articulo` (`idarticulo`, `idcategoria`, `articulo`, `descripcion_corta`, `descripcion_completa`, `precio`, `existencias`, `fecha_registro`, `imagen`) VALUES
(82, 10, 'Vino Blanco Chateau Prieuré Lichine 2007 .750', '', 'Es el segundo vino en crecimiento en Francia, es complejo y de mucha calidad, de color rubí oscuro y profundo, de mucho cuerpo y denso, en nariz se siente aterciopelado y con un aroma a bayas, con té floral, de taninos algo ásperos, con un acabado largo y digno, sinate su frescura cada vez que resbale por tu paladar.\n\nTipo de bebida: Vino Blanco.\nVolumen de alcohol: 12.5%.\nContenido: 750ml.\nCrianza: 18 meses de crianza en barricas de roble.\nPaís de origen: Francia.\nPresentación: Botella.\nMaridaje: carnes rojas, guisos de carne de cerdo, carne de caballo, canelones y queso payoyo.\nTipo de Uvas: Merlot, Cabernet Sauvignon, Cabernet Franc, Semillón y Petit Verdot', '1499.00', 1, '2014-04-26', 'productos/vinos/Vino Blanco Chateau Prieuré Lichine 2007 .750.jpg'),
(83, 10, 'Vino Tinto Chateau Petrus 2009 .750', '', 'Vino Tinto Chateau Petrus 2009 .750\nSe puede beber inmediatamenten un vino grande para la época, ofrece un color morado oscuro, aroma a moras y cerezas negras, con un poco de madera de cedro, de mucho cuerpo, final en boca con sensación suave y fresca. Taninos sedosos.\n\nTipo de bebida: Vino Tinto.\nVolumen de alcohol: 14.%.\nContenido: 750ml.\nCrianza: envejecido 12 meses en barricas de roble Francés.\nPaís de origen: Francia\nPresentación: Botella.\nMaridaje: Carnes Rojas Guisadas, Caza Mayor.\nTipo de Uva: Cabernet sauvignon, Merlot y Burdeos Coupage.', '162900.00', 1, '2014-04-26', 'productos/vinos/Vino Tinto Chateau Petrus 2009 .750.jpg'),
(84, 10, 'Whisky J. Walker Etiqueta Azul', 'El arte de mezcla (blending).', 'Tipo de vino: Whisky.\nContenido: 750 ml.\nPaís de Origen: Escocia.\nPresentación: Una Botella', '3800.00', 1, '2014-04-26', 'productos/vinos/Whisky J. Walker Etiqueta Azul.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `busquedareciente`
--

CREATE TABLE IF NOT EXISTS `busquedareciente` (
  `idusuario` int(11) NOT NULL,
  `criterio1` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `criterio2` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `criterio3` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`idusuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `categoria`
--

CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`idcategoria`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci AUTO_INCREMENT=11 ;

--
-- Volcado de datos para la tabla `categoria`
--

INSERT INTO `categoria` (`idcategoria`, `nombre_categoria`) VALUES
(1, 'BELLEZA'),
(2, 'ELECTRODOMESTICOS'),
(3, 'JOYERIA'),
(4, 'LIBROS'),
(5, 'MODA'),
(6, 'MUSICA'),
(7, 'OFICINA'),
(8, 'PERFUMES'),
(9, 'TECNOLOGIA'),
(10, 'VINOS');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `nombres` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `apellido_paterno` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `apellido_materno` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `edad` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `correo_electronico` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `password` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`idusuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `venta`
--

CREATE TABLE IF NOT EXISTS `venta` (
  `idventa` int(11) NOT NULL AUTO_INCREMENT,
  `idarticulo` varchar(45) COLLATE utf8_spanish_ci NOT NULL,
  `idcategoria` varchar(45) COLLATE utf8_spanish_ci NOT NULL,
  `precio` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`idventa`,`idarticulo`,`idcategoria`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci AUTO_INCREMENT=1 ;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `articulo`
--
ALTER TABLE `articulo`
  ADD CONSTRAINT `fk_articulo_categoria` FOREIGN KEY (`idcategoria`) REFERENCES `categoria` (`idcategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
